<?xml version="1.0" encoding="utf-8"?><Database Name="GalAMM_test" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SRVGALDB2;Initial Catalog=GalAMM_test;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="GalAMM_testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ПроизводственнаяЕдиница" Member="ПроизводственнаяЕдиницаs">
    <Type Name="ПроизводственнаяЕдиница">
      <Column Name="Oid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ДатаСоздания" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Создатель" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="СозданПользователем" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ДатаПоследнейМодификации" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Редактор" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ИзмененПользователем" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ExternalID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="СтроковоеПредставление" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Код" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TreeOids" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Вышестоящий" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="СтатусОбъекта" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ДатаИзмененияСтатуса" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ИзмененияПользователя" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ПолноеНаименование" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="Площадка" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="УровеньПЕ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ДатаВвода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаСнятия" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Субподрядная" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Субподрядчик" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Руководитель" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="КоличествоСотрудников" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КоличествоОборудования" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ОтвечаетЗаПланРабот" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="График" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ТипМестаХранения" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="УчетПоСкладскимЯчейкам" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="СтатусЗапаса" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ПорядокПриКомплектации" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ВлияетНаОстатки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ОстаткиДоступныДляОбещания" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ОстаткиДоступныДляРезерв" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ОстаткиДоступныДляПлан" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="КонтрольКомплектацииПриЗапуске" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="РегистрацияЗапуска" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="РегистрацияВыпуска" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OptimisticLockField" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCRecord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ОграничениеМощности" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="МВЗ" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="СотрудникиИспользуютТабель" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExternalID2" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="УчетМОЛ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Порядок" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КоэфПриРасчетеДлитПеределовТО" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ПризнакСинхронизации" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="HistoryCreateActionExecutor" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HistoryCreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HistoryModifyActionExecutor" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HistoryModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PriceRecount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ПересчетЦен" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.viewForComtecBalanceCheck" Member="viewForComtecBalanceChecks">
    <Type Name="viewForComtecBalanceCheck">
      <Column Name="np" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="storeName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="qty" Type="System.Decimal" DbType="Decimal(24,8)" CanBeNull="true" />
      <Column Name="dt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="party" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>