#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GalAMM_test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertПроизводственнаяЕдиница(ПроизводственнаяЕдиница instance);
    partial void UpdateПроизводственнаяЕдиница(ПроизводственнаяЕдиница instance);
    partial void DeleteПроизводственнаяЕдиница(ПроизводственнаяЕдиница instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DataAccess.Properties.Settings.Default.GalAMM_testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ПроизводственнаяЕдиница> ПроизводственнаяЕдиницаs
		{
			get
			{
				return this.GetTable<ПроизводственнаяЕдиница>();
			}
		}
		
		public System.Data.Linq.Table<viewForComtecBalanceCheck> viewForComtecBalanceChecks
		{
			get
			{
				return this.GetTable<viewForComtecBalanceCheck>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ПроизводственнаяЕдиница")]
	public partial class ПроизводственнаяЕдиница : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Oid;
		
		private System.Nullable<System.DateTime> _ДатаСоздания;
		
		private string _Создатель;
		
		private string _СозданПользователем;
		
		private System.Nullable<System.DateTime> _ДатаПоследнейМодификации;
		
		private string _Редактор;
		
		private string _ИзмененПользователем;
		
		private string _ExternalID;
		
		private string _СтроковоеПредставление;
		
		private string _Код;
		
		private string _Наименование;
		
		private string _TreeOids;
		
		private System.Nullable<System.Guid> _Вышестоящий;
		
		private string _ImageName;
		
		private System.Nullable<int> _СтатусОбъекта;
		
		private System.Nullable<System.DateTime> _ДатаИзмененияСтатуса;
		
		private string _ИзмененияПользователя;
		
		private string _ПолноеНаименование;
		
		private System.Nullable<System.Guid> _Площадка;
		
		private System.Nullable<int> _УровеньПЕ;
		
		private System.Nullable<System.DateTime> _ДатаВвода;
		
		private System.Nullable<System.DateTime> _ДатаСнятия;
		
		private System.Nullable<bool> _Субподрядная;
		
		private System.Nullable<System.Guid> _Субподрядчик;
		
		private System.Nullable<System.Guid> _Руководитель;
		
		private System.Nullable<int> _КоличествоСотрудников;
		
		private System.Nullable<int> _КоличествоОборудования;
		
		private System.Nullable<bool> _ОтвечаетЗаПланРабот;
		
		private System.Nullable<System.Guid> _График;
		
		private System.Nullable<int> _ТипМестаХранения;
		
		private System.Nullable<int> _УчетПоСкладскимЯчейкам;
		
		private System.Nullable<int> _СтатусЗапаса;
		
		private System.Nullable<int> _ПорядокПриКомплектации;
		
		private System.Nullable<bool> _ВлияетНаОстатки;
		
		private System.Nullable<bool> _ОстаткиДоступныДляОбещания;
		
		private System.Nullable<bool> _ОстаткиДоступныДляРезерв;
		
		private System.Nullable<bool> _ОстаткиДоступныДляПлан;
		
		private System.Nullable<int> _КонтрольКомплектацииПриЗапуске;
		
		private System.Nullable<int> _РегистрацияЗапуска;
		
		private System.Nullable<int> _РегистрацияВыпуска;
		
		private System.Nullable<int> _OptimisticLockField;
		
		private System.Nullable<int> _GCRecord;
		
		private System.Nullable<int> _ОграничениеМощности;
		
		private System.Nullable<System.Guid> _МВЗ;
		
		private System.Nullable<bool> _СотрудникиИспользуютТабель;
		
		private string _ExternalID2;
		
		private System.Nullable<int> _УчетМОЛ;
		
		private System.Nullable<int> _Порядок;
		
		private System.Nullable<decimal> _КоэфПриРасчетеДлитПеределовТО;
		
		private System.Nullable<bool> _ПризнакСинхронизации;
		
		private System.Nullable<decimal> _TransactionId;
		
		private string _HistoryCreateActionExecutor;
		
		private System.Nullable<System.DateTime> _HistoryCreateDate;
		
		private string _HistoryModifyActionExecutor;
		
		private System.Nullable<System.DateTime> _HistoryModifyDate;
		
		private System.Nullable<bool> _PriceRecount;
		
		private System.Nullable<bool> _ПересчетЦен;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOidChanging(System.Guid value);
    partial void OnOidChanged();
    partial void OnДатаСозданияChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаСозданияChanged();
    partial void OnСоздательChanging(string value);
    partial void OnСоздательChanged();
    partial void OnСозданПользователемChanging(string value);
    partial void OnСозданПользователемChanged();
    partial void OnДатаПоследнейМодификацииChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаПоследнейМодификацииChanged();
    partial void OnРедакторChanging(string value);
    partial void OnРедакторChanged();
    partial void OnИзмененПользователемChanging(string value);
    partial void OnИзмененПользователемChanged();
    partial void OnExternalIDChanging(string value);
    partial void OnExternalIDChanged();
    partial void OnСтроковоеПредставлениеChanging(string value);
    partial void OnСтроковоеПредставлениеChanged();
    partial void OnКодChanging(string value);
    partial void OnКодChanged();
    partial void OnНаименованиеChanging(string value);
    partial void OnНаименованиеChanged();
    partial void OnTreeOidsChanging(string value);
    partial void OnTreeOidsChanged();
    partial void OnВышестоящийChanging(System.Nullable<System.Guid> value);
    partial void OnВышестоящийChanged();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    partial void OnСтатусОбъектаChanging(System.Nullable<int> value);
    partial void OnСтатусОбъектаChanged();
    partial void OnДатаИзмененияСтатусаChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаИзмененияСтатусаChanged();
    partial void OnИзмененияПользователяChanging(string value);
    partial void OnИзмененияПользователяChanged();
    partial void OnПолноеНаименованиеChanging(string value);
    partial void OnПолноеНаименованиеChanged();
    partial void OnПлощадкаChanging(System.Nullable<System.Guid> value);
    partial void OnПлощадкаChanged();
    partial void OnУровеньПЕChanging(System.Nullable<int> value);
    partial void OnУровеньПЕChanged();
    partial void OnДатаВводаChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаВводаChanged();
    partial void OnДатаСнятияChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаСнятияChanged();
    partial void OnСубподряднаяChanging(System.Nullable<bool> value);
    partial void OnСубподряднаяChanged();
    partial void OnСубподрядчикChanging(System.Nullable<System.Guid> value);
    partial void OnСубподрядчикChanged();
    partial void OnРуководительChanging(System.Nullable<System.Guid> value);
    partial void OnРуководительChanged();
    partial void OnКоличествоСотрудниковChanging(System.Nullable<int> value);
    partial void OnКоличествоСотрудниковChanged();
    partial void OnКоличествоОборудованияChanging(System.Nullable<int> value);
    partial void OnКоличествоОборудованияChanged();
    partial void OnОтвечаетЗаПланРаботChanging(System.Nullable<bool> value);
    partial void OnОтвечаетЗаПланРаботChanged();
    partial void OnГрафикChanging(System.Nullable<System.Guid> value);
    partial void OnГрафикChanged();
    partial void OnТипМестаХраненияChanging(System.Nullable<int> value);
    partial void OnТипМестаХраненияChanged();
    partial void OnУчетПоСкладскимЯчейкамChanging(System.Nullable<int> value);
    partial void OnУчетПоСкладскимЯчейкамChanged();
    partial void OnСтатусЗапасаChanging(System.Nullable<int> value);
    partial void OnСтатусЗапасаChanged();
    partial void OnПорядокПриКомплектацииChanging(System.Nullable<int> value);
    partial void OnПорядокПриКомплектацииChanged();
    partial void OnВлияетНаОстаткиChanging(System.Nullable<bool> value);
    partial void OnВлияетНаОстаткиChanged();
    partial void OnОстаткиДоступныДляОбещанияChanging(System.Nullable<bool> value);
    partial void OnОстаткиДоступныДляОбещанияChanged();
    partial void OnОстаткиДоступныДляРезервChanging(System.Nullable<bool> value);
    partial void OnОстаткиДоступныДляРезервChanged();
    partial void OnОстаткиДоступныДляПланChanging(System.Nullable<bool> value);
    partial void OnОстаткиДоступныДляПланChanged();
    partial void OnКонтрольКомплектацииПриЗапускеChanging(System.Nullable<int> value);
    partial void OnКонтрольКомплектацииПриЗапускеChanged();
    partial void OnРегистрацияЗапускаChanging(System.Nullable<int> value);
    partial void OnРегистрацияЗапускаChanged();
    partial void OnРегистрацияВыпускаChanging(System.Nullable<int> value);
    partial void OnРегистрацияВыпускаChanged();
    partial void OnOptimisticLockFieldChanging(System.Nullable<int> value);
    partial void OnOptimisticLockFieldChanged();
    partial void OnGCRecordChanging(System.Nullable<int> value);
    partial void OnGCRecordChanged();
    partial void OnОграничениеМощностиChanging(System.Nullable<int> value);
    partial void OnОграничениеМощностиChanged();
    partial void OnМВЗChanging(System.Nullable<System.Guid> value);
    partial void OnМВЗChanged();
    partial void OnСотрудникиИспользуютТабельChanging(System.Nullable<bool> value);
    partial void OnСотрудникиИспользуютТабельChanged();
    partial void OnExternalID2Changing(string value);
    partial void OnExternalID2Changed();
    partial void OnУчетМОЛChanging(System.Nullable<int> value);
    partial void OnУчетМОЛChanged();
    partial void OnПорядокChanging(System.Nullable<int> value);
    partial void OnПорядокChanged();
    partial void OnКоэфПриРасчетеДлитПеределовТОChanging(System.Nullable<decimal> value);
    partial void OnКоэфПриРасчетеДлитПеределовТОChanged();
    partial void OnПризнакСинхронизацииChanging(System.Nullable<bool> value);
    partial void OnПризнакСинхронизацииChanged();
    partial void OnTransactionIdChanging(System.Nullable<decimal> value);
    partial void OnTransactionIdChanged();
    partial void OnHistoryCreateActionExecutorChanging(string value);
    partial void OnHistoryCreateActionExecutorChanged();
    partial void OnHistoryCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHistoryCreateDateChanged();
    partial void OnHistoryModifyActionExecutorChanging(string value);
    partial void OnHistoryModifyActionExecutorChanged();
    partial void OnHistoryModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHistoryModifyDateChanged();
    partial void OnPriceRecountChanging(System.Nullable<bool> value);
    partial void OnPriceRecountChanged();
    partial void OnПересчетЦенChanging(System.Nullable<bool> value);
    partial void OnПересчетЦенChanged();
    #endregion
		
		public ПроизводственнаяЕдиница()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Oid
		{
			get
			{
				return this._Oid;
			}
			set
			{
				if ((this._Oid != value))
				{
					this.OnOidChanging(value);
					this.SendPropertyChanging();
					this._Oid = value;
					this.SendPropertyChanged("Oid");
					this.OnOidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаСоздания", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаСоздания
		{
			get
			{
				return this._ДатаСоздания;
			}
			set
			{
				if ((this._ДатаСоздания != value))
				{
					this.OnДатаСозданияChanging(value);
					this.SendPropertyChanging();
					this._ДатаСоздания = value;
					this.SendPropertyChanged("ДатаСоздания");
					this.OnДатаСозданияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Создатель", DbType="NVarChar(100)")]
		public string Создатель
		{
			get
			{
				return this._Создатель;
			}
			set
			{
				if ((this._Создатель != value))
				{
					this.OnСоздательChanging(value);
					this.SendPropertyChanging();
					this._Создатель = value;
					this.SendPropertyChanged("Создатель");
					this.OnСоздательChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СозданПользователем", DbType="NVarChar(100)")]
		public string СозданПользователем
		{
			get
			{
				return this._СозданПользователем;
			}
			set
			{
				if ((this._СозданПользователем != value))
				{
					this.OnСозданПользователемChanging(value);
					this.SendPropertyChanging();
					this._СозданПользователем = value;
					this.SendPropertyChanged("СозданПользователем");
					this.OnСозданПользователемChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаПоследнейМодификации", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаПоследнейМодификации
		{
			get
			{
				return this._ДатаПоследнейМодификации;
			}
			set
			{
				if ((this._ДатаПоследнейМодификации != value))
				{
					this.OnДатаПоследнейМодификацииChanging(value);
					this.SendPropertyChanging();
					this._ДатаПоследнейМодификации = value;
					this.SendPropertyChanged("ДатаПоследнейМодификации");
					this.OnДатаПоследнейМодификацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Редактор", DbType="NVarChar(100)")]
		public string Редактор
		{
			get
			{
				return this._Редактор;
			}
			set
			{
				if ((this._Редактор != value))
				{
					this.OnРедакторChanging(value);
					this.SendPropertyChanging();
					this._Редактор = value;
					this.SendPropertyChanged("Редактор");
					this.OnРедакторChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ИзмененПользователем", DbType="NVarChar(100)")]
		public string ИзмененПользователем
		{
			get
			{
				return this._ИзмененПользователем;
			}
			set
			{
				if ((this._ИзмененПользователем != value))
				{
					this.OnИзмененПользователемChanging(value);
					this.SendPropertyChanging();
					this._ИзмененПользователем = value;
					this.SendPropertyChanged("ИзмененПользователем");
					this.OnИзмененПользователемChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExternalID", DbType="NVarChar(150)")]
		public string ExternalID
		{
			get
			{
				return this._ExternalID;
			}
			set
			{
				if ((this._ExternalID != value))
				{
					this.OnExternalIDChanging(value);
					this.SendPropertyChanging();
					this._ExternalID = value;
					this.SendPropertyChanged("ExternalID");
					this.OnExternalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СтроковоеПредставление", DbType="NVarChar(255)")]
		public string СтроковоеПредставление
		{
			get
			{
				return this._СтроковоеПредставление;
			}
			set
			{
				if ((this._СтроковоеПредставление != value))
				{
					this.OnСтроковоеПредставлениеChanging(value);
					this.SendPropertyChanging();
					this._СтроковоеПредставление = value;
					this.SendPropertyChanged("СтроковоеПредставление");
					this.OnСтроковоеПредставлениеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Код", DbType="NVarChar(80)")]
		public string Код
		{
			get
			{
				return this._Код;
			}
			set
			{
				if ((this._Код != value))
				{
					this.OnКодChanging(value);
					this.SendPropertyChanging();
					this._Код = value;
					this.SendPropertyChanged("Код");
					this.OnКодChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наименование", DbType="NVarChar(150)")]
		public string Наименование
		{
			get
			{
				return this._Наименование;
			}
			set
			{
				if ((this._Наименование != value))
				{
					this.OnНаименованиеChanging(value);
					this.SendPropertyChanging();
					this._Наименование = value;
					this.SendPropertyChanged("Наименование");
					this.OnНаименованиеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeOids", DbType="NVarChar(4000)")]
		public string TreeOids
		{
			get
			{
				return this._TreeOids;
			}
			set
			{
				if ((this._TreeOids != value))
				{
					this.OnTreeOidsChanging(value);
					this.SendPropertyChanging();
					this._TreeOids = value;
					this.SendPropertyChanged("TreeOids");
					this.OnTreeOidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Вышестоящий", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Вышестоящий
		{
			get
			{
				return this._Вышестоящий;
			}
			set
			{
				if ((this._Вышестоящий != value))
				{
					this.OnВышестоящийChanging(value);
					this.SendPropertyChanging();
					this._Вышестоящий = value;
					this.SendPropertyChanged("Вышестоящий");
					this.OnВышестоящийChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(100)")]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СтатусОбъекта", DbType="Int")]
		public System.Nullable<int> СтатусОбъекта
		{
			get
			{
				return this._СтатусОбъекта;
			}
			set
			{
				if ((this._СтатусОбъекта != value))
				{
					this.OnСтатусОбъектаChanging(value);
					this.SendPropertyChanging();
					this._СтатусОбъекта = value;
					this.SendPropertyChanged("СтатусОбъекта");
					this.OnСтатусОбъектаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаИзмененияСтатуса", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаИзмененияСтатуса
		{
			get
			{
				return this._ДатаИзмененияСтатуса;
			}
			set
			{
				if ((this._ДатаИзмененияСтатуса != value))
				{
					this.OnДатаИзмененияСтатусаChanging(value);
					this.SendPropertyChanging();
					this._ДатаИзмененияСтатуса = value;
					this.SendPropertyChanged("ДатаИзмененияСтатуса");
					this.OnДатаИзмененияСтатусаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ИзмененияПользователя", DbType="NVarChar(100)")]
		public string ИзмененияПользователя
		{
			get
			{
				return this._ИзмененияПользователя;
			}
			set
			{
				if ((this._ИзмененияПользователя != value))
				{
					this.OnИзмененияПользователяChanging(value);
					this.SendPropertyChanging();
					this._ИзмененияПользователя = value;
					this.SendPropertyChanged("ИзмененияПользователя");
					this.OnИзмененияПользователяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ПолноеНаименование", DbType="NVarChar(350)")]
		public string ПолноеНаименование
		{
			get
			{
				return this._ПолноеНаименование;
			}
			set
			{
				if ((this._ПолноеНаименование != value))
				{
					this.OnПолноеНаименованиеChanging(value);
					this.SendPropertyChanging();
					this._ПолноеНаименование = value;
					this.SendPropertyChanged("ПолноеНаименование");
					this.OnПолноеНаименованиеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Площадка", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Площадка
		{
			get
			{
				return this._Площадка;
			}
			set
			{
				if ((this._Площадка != value))
				{
					this.OnПлощадкаChanging(value);
					this.SendPropertyChanging();
					this._Площадка = value;
					this.SendPropertyChanged("Площадка");
					this.OnПлощадкаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_УровеньПЕ", DbType="Int")]
		public System.Nullable<int> УровеньПЕ
		{
			get
			{
				return this._УровеньПЕ;
			}
			set
			{
				if ((this._УровеньПЕ != value))
				{
					this.OnУровеньПЕChanging(value);
					this.SendPropertyChanging();
					this._УровеньПЕ = value;
					this.SendPropertyChanged("УровеньПЕ");
					this.OnУровеньПЕChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаВвода", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаВвода
		{
			get
			{
				return this._ДатаВвода;
			}
			set
			{
				if ((this._ДатаВвода != value))
				{
					this.OnДатаВводаChanging(value);
					this.SendPropertyChanging();
					this._ДатаВвода = value;
					this.SendPropertyChanged("ДатаВвода");
					this.OnДатаВводаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаСнятия", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаСнятия
		{
			get
			{
				return this._ДатаСнятия;
			}
			set
			{
				if ((this._ДатаСнятия != value))
				{
					this.OnДатаСнятияChanging(value);
					this.SendPropertyChanging();
					this._ДатаСнятия = value;
					this.SendPropertyChanged("ДатаСнятия");
					this.OnДатаСнятияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Субподрядная", DbType="Bit")]
		public System.Nullable<bool> Субподрядная
		{
			get
			{
				return this._Субподрядная;
			}
			set
			{
				if ((this._Субподрядная != value))
				{
					this.OnСубподряднаяChanging(value);
					this.SendPropertyChanging();
					this._Субподрядная = value;
					this.SendPropertyChanged("Субподрядная");
					this.OnСубподряднаяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Субподрядчик", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Субподрядчик
		{
			get
			{
				return this._Субподрядчик;
			}
			set
			{
				if ((this._Субподрядчик != value))
				{
					this.OnСубподрядчикChanging(value);
					this.SendPropertyChanging();
					this._Субподрядчик = value;
					this.SendPropertyChanged("Субподрядчик");
					this.OnСубподрядчикChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Руководитель", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Руководитель
		{
			get
			{
				return this._Руководитель;
			}
			set
			{
				if ((this._Руководитель != value))
				{
					this.OnРуководительChanging(value);
					this.SendPropertyChanging();
					this._Руководитель = value;
					this.SendPropertyChanged("Руководитель");
					this.OnРуководительChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КоличествоСотрудников", DbType="Int")]
		public System.Nullable<int> КоличествоСотрудников
		{
			get
			{
				return this._КоличествоСотрудников;
			}
			set
			{
				if ((this._КоличествоСотрудников != value))
				{
					this.OnКоличествоСотрудниковChanging(value);
					this.SendPropertyChanging();
					this._КоличествоСотрудников = value;
					this.SendPropertyChanged("КоличествоСотрудников");
					this.OnКоличествоСотрудниковChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КоличествоОборудования", DbType="Int")]
		public System.Nullable<int> КоличествоОборудования
		{
			get
			{
				return this._КоличествоОборудования;
			}
			set
			{
				if ((this._КоличествоОборудования != value))
				{
					this.OnКоличествоОборудованияChanging(value);
					this.SendPropertyChanging();
					this._КоличествоОборудования = value;
					this.SendPropertyChanged("КоличествоОборудования");
					this.OnКоличествоОборудованияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОтвечаетЗаПланРабот", DbType="Bit")]
		public System.Nullable<bool> ОтвечаетЗаПланРабот
		{
			get
			{
				return this._ОтвечаетЗаПланРабот;
			}
			set
			{
				if ((this._ОтвечаетЗаПланРабот != value))
				{
					this.OnОтвечаетЗаПланРаботChanging(value);
					this.SendPropertyChanging();
					this._ОтвечаетЗаПланРабот = value;
					this.SendPropertyChanged("ОтвечаетЗаПланРабот");
					this.OnОтвечаетЗаПланРаботChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_График", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> График
		{
			get
			{
				return this._График;
			}
			set
			{
				if ((this._График != value))
				{
					this.OnГрафикChanging(value);
					this.SendPropertyChanging();
					this._График = value;
					this.SendPropertyChanged("График");
					this.OnГрафикChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ТипМестаХранения", DbType="Int")]
		public System.Nullable<int> ТипМестаХранения
		{
			get
			{
				return this._ТипМестаХранения;
			}
			set
			{
				if ((this._ТипМестаХранения != value))
				{
					this.OnТипМестаХраненияChanging(value);
					this.SendPropertyChanging();
					this._ТипМестаХранения = value;
					this.SendPropertyChanged("ТипМестаХранения");
					this.OnТипМестаХраненияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_УчетПоСкладскимЯчейкам", DbType="Int")]
		public System.Nullable<int> УчетПоСкладскимЯчейкам
		{
			get
			{
				return this._УчетПоСкладскимЯчейкам;
			}
			set
			{
				if ((this._УчетПоСкладскимЯчейкам != value))
				{
					this.OnУчетПоСкладскимЯчейкамChanging(value);
					this.SendPropertyChanging();
					this._УчетПоСкладскимЯчейкам = value;
					this.SendPropertyChanged("УчетПоСкладскимЯчейкам");
					this.OnУчетПоСкладскимЯчейкамChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СтатусЗапаса", DbType="Int")]
		public System.Nullable<int> СтатусЗапаса
		{
			get
			{
				return this._СтатусЗапаса;
			}
			set
			{
				if ((this._СтатусЗапаса != value))
				{
					this.OnСтатусЗапасаChanging(value);
					this.SendPropertyChanging();
					this._СтатусЗапаса = value;
					this.SendPropertyChanged("СтатусЗапаса");
					this.OnСтатусЗапасаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ПорядокПриКомплектации", DbType="Int")]
		public System.Nullable<int> ПорядокПриКомплектации
		{
			get
			{
				return this._ПорядокПриКомплектации;
			}
			set
			{
				if ((this._ПорядокПриКомплектации != value))
				{
					this.OnПорядокПриКомплектацииChanging(value);
					this.SendPropertyChanging();
					this._ПорядокПриКомплектации = value;
					this.SendPropertyChanged("ПорядокПриКомплектации");
					this.OnПорядокПриКомплектацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ВлияетНаОстатки", DbType="Bit")]
		public System.Nullable<bool> ВлияетНаОстатки
		{
			get
			{
				return this._ВлияетНаОстатки;
			}
			set
			{
				if ((this._ВлияетНаОстатки != value))
				{
					this.OnВлияетНаОстаткиChanging(value);
					this.SendPropertyChanging();
					this._ВлияетНаОстатки = value;
					this.SendPropertyChanged("ВлияетНаОстатки");
					this.OnВлияетНаОстаткиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОстаткиДоступныДляОбещания", DbType="Bit")]
		public System.Nullable<bool> ОстаткиДоступныДляОбещания
		{
			get
			{
				return this._ОстаткиДоступныДляОбещания;
			}
			set
			{
				if ((this._ОстаткиДоступныДляОбещания != value))
				{
					this.OnОстаткиДоступныДляОбещанияChanging(value);
					this.SendPropertyChanging();
					this._ОстаткиДоступныДляОбещания = value;
					this.SendPropertyChanged("ОстаткиДоступныДляОбещания");
					this.OnОстаткиДоступныДляОбещанияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОстаткиДоступныДляРезерв", DbType="Bit")]
		public System.Nullable<bool> ОстаткиДоступныДляРезерв
		{
			get
			{
				return this._ОстаткиДоступныДляРезерв;
			}
			set
			{
				if ((this._ОстаткиДоступныДляРезерв != value))
				{
					this.OnОстаткиДоступныДляРезервChanging(value);
					this.SendPropertyChanging();
					this._ОстаткиДоступныДляРезерв = value;
					this.SendPropertyChanged("ОстаткиДоступныДляРезерв");
					this.OnОстаткиДоступныДляРезервChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОстаткиДоступныДляПлан", DbType="Bit")]
		public System.Nullable<bool> ОстаткиДоступныДляПлан
		{
			get
			{
				return this._ОстаткиДоступныДляПлан;
			}
			set
			{
				if ((this._ОстаткиДоступныДляПлан != value))
				{
					this.OnОстаткиДоступныДляПланChanging(value);
					this.SendPropertyChanging();
					this._ОстаткиДоступныДляПлан = value;
					this.SendPropertyChanged("ОстаткиДоступныДляПлан");
					this.OnОстаткиДоступныДляПланChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КонтрольКомплектацииПриЗапуске", DbType="Int")]
		public System.Nullable<int> КонтрольКомплектацииПриЗапуске
		{
			get
			{
				return this._КонтрольКомплектацииПриЗапуске;
			}
			set
			{
				if ((this._КонтрольКомплектацииПриЗапуске != value))
				{
					this.OnКонтрольКомплектацииПриЗапускеChanging(value);
					this.SendPropertyChanging();
					this._КонтрольКомплектацииПриЗапуске = value;
					this.SendPropertyChanged("КонтрольКомплектацииПриЗапуске");
					this.OnКонтрольКомплектацииПриЗапускеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_РегистрацияЗапуска", DbType="Int")]
		public System.Nullable<int> РегистрацияЗапуска
		{
			get
			{
				return this._РегистрацияЗапуска;
			}
			set
			{
				if ((this._РегистрацияЗапуска != value))
				{
					this.OnРегистрацияЗапускаChanging(value);
					this.SendPropertyChanging();
					this._РегистрацияЗапуска = value;
					this.SendPropertyChanged("РегистрацияЗапуска");
					this.OnРегистрацияЗапускаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_РегистрацияВыпуска", DbType="Int")]
		public System.Nullable<int> РегистрацияВыпуска
		{
			get
			{
				return this._РегистрацияВыпуска;
			}
			set
			{
				if ((this._РегистрацияВыпуска != value))
				{
					this.OnРегистрацияВыпускаChanging(value);
					this.SendPropertyChanging();
					this._РегистрацияВыпуска = value;
					this.SendPropertyChanged("РегистрацияВыпуска");
					this.OnРегистрацияВыпускаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptimisticLockField", DbType="Int")]
		public System.Nullable<int> OptimisticLockField
		{
			get
			{
				return this._OptimisticLockField;
			}
			set
			{
				if ((this._OptimisticLockField != value))
				{
					this.OnOptimisticLockFieldChanging(value);
					this.SendPropertyChanging();
					this._OptimisticLockField = value;
					this.SendPropertyChanged("OptimisticLockField");
					this.OnOptimisticLockFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCRecord", DbType="Int")]
		public System.Nullable<int> GCRecord
		{
			get
			{
				return this._GCRecord;
			}
			set
			{
				if ((this._GCRecord != value))
				{
					this.OnGCRecordChanging(value);
					this.SendPropertyChanging();
					this._GCRecord = value;
					this.SendPropertyChanged("GCRecord");
					this.OnGCRecordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОграничениеМощности", DbType="Int")]
		public System.Nullable<int> ОграничениеМощности
		{
			get
			{
				return this._ОграничениеМощности;
			}
			set
			{
				if ((this._ОграничениеМощности != value))
				{
					this.OnОграничениеМощностиChanging(value);
					this.SendPropertyChanging();
					this._ОграничениеМощности = value;
					this.SendPropertyChanged("ОграничениеМощности");
					this.OnОграничениеМощностиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_МВЗ", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> МВЗ
		{
			get
			{
				return this._МВЗ;
			}
			set
			{
				if ((this._МВЗ != value))
				{
					this.OnМВЗChanging(value);
					this.SendPropertyChanging();
					this._МВЗ = value;
					this.SendPropertyChanged("МВЗ");
					this.OnМВЗChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СотрудникиИспользуютТабель", DbType="Bit")]
		public System.Nullable<bool> СотрудникиИспользуютТабель
		{
			get
			{
				return this._СотрудникиИспользуютТабель;
			}
			set
			{
				if ((this._СотрудникиИспользуютТабель != value))
				{
					this.OnСотрудникиИспользуютТабельChanging(value);
					this.SendPropertyChanging();
					this._СотрудникиИспользуютТабель = value;
					this.SendPropertyChanged("СотрудникиИспользуютТабель");
					this.OnСотрудникиИспользуютТабельChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExternalID2", DbType="NVarChar(150)")]
		public string ExternalID2
		{
			get
			{
				return this._ExternalID2;
			}
			set
			{
				if ((this._ExternalID2 != value))
				{
					this.OnExternalID2Changing(value);
					this.SendPropertyChanging();
					this._ExternalID2 = value;
					this.SendPropertyChanged("ExternalID2");
					this.OnExternalID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_УчетМОЛ", DbType="Int")]
		public System.Nullable<int> УчетМОЛ
		{
			get
			{
				return this._УчетМОЛ;
			}
			set
			{
				if ((this._УчетМОЛ != value))
				{
					this.OnУчетМОЛChanging(value);
					this.SendPropertyChanging();
					this._УчетМОЛ = value;
					this.SendPropertyChanged("УчетМОЛ");
					this.OnУчетМОЛChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Порядок", DbType="Int")]
		public System.Nullable<int> Порядок
		{
			get
			{
				return this._Порядок;
			}
			set
			{
				if ((this._Порядок != value))
				{
					this.OnПорядокChanging(value);
					this.SendPropertyChanging();
					this._Порядок = value;
					this.SendPropertyChanged("Порядок");
					this.OnПорядокChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КоэфПриРасчетеДлитПеределовТО", DbType="Money")]
		public System.Nullable<decimal> КоэфПриРасчетеДлитПеределовТО
		{
			get
			{
				return this._КоэфПриРасчетеДлитПеределовТО;
			}
			set
			{
				if ((this._КоэфПриРасчетеДлитПеределовТО != value))
				{
					this.OnКоэфПриРасчетеДлитПеределовТОChanging(value);
					this.SendPropertyChanging();
					this._КоэфПриРасчетеДлитПеределовТО = value;
					this.SendPropertyChanged("КоэфПриРасчетеДлитПеределовТО");
					this.OnКоэфПриРасчетеДлитПеределовТОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ПризнакСинхронизации", DbType="Bit")]
		public System.Nullable<bool> ПризнакСинхронизации
		{
			get
			{
				return this._ПризнакСинхронизации;
			}
			set
			{
				if ((this._ПризнакСинхронизации != value))
				{
					this.OnПризнакСинхронизацииChanging(value);
					this.SendPropertyChanging();
					this._ПризнакСинхронизации = value;
					this.SendPropertyChanged("ПризнакСинхронизации");
					this.OnПризнакСинхронизацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionId", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> TransactionId
		{
			get
			{
				return this._TransactionId;
			}
			set
			{
				if ((this._TransactionId != value))
				{
					this.OnTransactionIdChanging(value);
					this.SendPropertyChanging();
					this._TransactionId = value;
					this.SendPropertyChanged("TransactionId");
					this.OnTransactionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoryCreateActionExecutor", DbType="NVarChar(100)")]
		public string HistoryCreateActionExecutor
		{
			get
			{
				return this._HistoryCreateActionExecutor;
			}
			set
			{
				if ((this._HistoryCreateActionExecutor != value))
				{
					this.OnHistoryCreateActionExecutorChanging(value);
					this.SendPropertyChanging();
					this._HistoryCreateActionExecutor = value;
					this.SendPropertyChanged("HistoryCreateActionExecutor");
					this.OnHistoryCreateActionExecutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoryCreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> HistoryCreateDate
		{
			get
			{
				return this._HistoryCreateDate;
			}
			set
			{
				if ((this._HistoryCreateDate != value))
				{
					this.OnHistoryCreateDateChanging(value);
					this.SendPropertyChanging();
					this._HistoryCreateDate = value;
					this.SendPropertyChanged("HistoryCreateDate");
					this.OnHistoryCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoryModifyActionExecutor", DbType="NVarChar(100)")]
		public string HistoryModifyActionExecutor
		{
			get
			{
				return this._HistoryModifyActionExecutor;
			}
			set
			{
				if ((this._HistoryModifyActionExecutor != value))
				{
					this.OnHistoryModifyActionExecutorChanging(value);
					this.SendPropertyChanging();
					this._HistoryModifyActionExecutor = value;
					this.SendPropertyChanged("HistoryModifyActionExecutor");
					this.OnHistoryModifyActionExecutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HistoryModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> HistoryModifyDate
		{
			get
			{
				return this._HistoryModifyDate;
			}
			set
			{
				if ((this._HistoryModifyDate != value))
				{
					this.OnHistoryModifyDateChanging(value);
					this.SendPropertyChanging();
					this._HistoryModifyDate = value;
					this.SendPropertyChanged("HistoryModifyDate");
					this.OnHistoryModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceRecount", DbType="Bit")]
		public System.Nullable<bool> PriceRecount
		{
			get
			{
				return this._PriceRecount;
			}
			set
			{
				if ((this._PriceRecount != value))
				{
					this.OnPriceRecountChanging(value);
					this.SendPropertyChanging();
					this._PriceRecount = value;
					this.SendPropertyChanged("PriceRecount");
					this.OnPriceRecountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ПересчетЦен", DbType="Bit")]
		public System.Nullable<bool> ПересчетЦен
		{
			get
			{
				return this._ПересчетЦен;
			}
			set
			{
				if ((this._ПересчетЦен != value))
				{
					this.OnПересчетЦенChanging(value);
					this.SendPropertyChanging();
					this._ПересчетЦен = value;
					this.SendPropertyChanged("ПересчетЦен");
					this.OnПересчетЦенChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewForComtecBalanceCheck")]
	public partial class viewForComtecBalanceCheck
	{
		
		private string _np;
		
		private string _storeName;
		
		private System.Nullable<decimal> _qty;
		
		private System.Nullable<System.DateTime> _dt;
		
		private string _party;
		
		public viewForComtecBalanceCheck()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_np", DbType="NVarChar(100)")]
		public string np
		{
			get
			{
				return this._np;
			}
			set
			{
				if ((this._np != value))
				{
					this._np = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storeName", DbType="NVarChar(150)")]
		public string storeName
		{
			get
			{
				return this._storeName;
			}
			set
			{
				if ((this._storeName != value))
				{
					this._storeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Decimal(24,8)")]
		public System.Nullable<decimal> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this._qty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this._dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_party", DbType="NVarChar(100)")]
		public string party
		{
			get
			{
				return this._party;
			}
			set
			{
				if ((this._party != value))
				{
					this._party = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
